// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern  uint20 needlemanWunsch ( uint2 read[100],  uint2 ref_genome[1000000]);
