// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xneedlemanwunsch.h"

extern XNeedlemanwunsch_Config XNeedlemanwunsch_ConfigTable[];

XNeedlemanwunsch_Config *XNeedlemanwunsch_LookupConfig(u16 DeviceId) {
	XNeedlemanwunsch_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNEEDLEMANWUNSCH_NUM_INSTANCES; Index++) {
		if (XNeedlemanwunsch_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNeedlemanwunsch_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNeedlemanwunsch_Initialize(XNeedlemanwunsch *InstancePtr, u16 DeviceId) {
	XNeedlemanwunsch_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNeedlemanwunsch_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNeedlemanwunsch_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

