# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch_AXILiteS_s_axi.v
  C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch_orig1.v
  C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch_score1.v
  C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch.v
}
read_xdc C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch.xdc
set_property used_in_implementation false [get_files C:/Users/Nathaniel2/hls1121/solution2/impl/verilog/needlemanWunsch.xdc]

synth_design -top needlemanWunsch -part xc7z020clg484-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef needlemanWunsch.dcp
catch { report_utilization -file needlemanWunsch_utilization_synth.rpt -pb needlemanWunsch_utilization_synth.pb }
