// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="needlemanWunsch,hls_ip_2015_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.088000,HLS_SYN_LAT=114500001,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=573,HLS_SYN_LUT=980}" *)

module needlemanWunsch (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        read_r_address0,
        read_r_ce0,
        read_r_q0,
        ref_genome_TDATA,
        ref_genome_TVALID,
        ref_genome_TREADY,
        interrupt
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 12'b1;
parameter    ap_ST_st2_fsm_1 = 12'b10;
parameter    ap_ST_st3_fsm_2 = 12'b100;
parameter    ap_ST_st4_fsm_3 = 12'b1000;
parameter    ap_ST_st5_fsm_4 = 12'b10000;
parameter    ap_ST_st6_fsm_5 = 12'b100000;
parameter    ap_ST_st7_fsm_6 = 12'b1000000;
parameter    ap_ST_st8_fsm_7 = 12'b10000000;
parameter    ap_ST_st9_fsm_8 = 12'b100000000;
parameter    ap_ST_st10_fsm_9 = 12'b1000000000;
parameter    ap_ST_st11_fsm_10 = 12'b10000000000;
parameter    ap_ST_st12_fsm_11 = 12'b100000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv20_1 = 20'b1;
parameter    ap_const_lv20_0 = 20'b00000000000000000000;
parameter    ap_const_lv32_FFFFFF9C = 32'b11111111111111111111111110011100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv64_63 = 64'b1100011;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv20_F4241 = 20'b11110100001001000001;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv20_2 = 20'b10;
parameter    ap_true = 1'b1;
parameter    C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
output  [4:0] read_r_address0;
output   read_r_ce0;
input  [7:0] read_r_q0;
input  [7:0] ref_genome_TDATA;
input   ref_genome_TVALID;
output   ref_genome_TREADY;
output   interrupt;

reg read_r_ce0;
reg ref_genome_TREADY;
reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm = 12'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_53;
reg    ap_ready;
wire   [19:0] ap_return;
wire    needlemanWunsch_AXILiteS_s_axi_U_ap_dummy_ce;
wire   [6:0] score2_addr_gep_fu_86_p3;
reg   [6:0] score2_addr_reg_463;
wire   [6:0] orig2_addr_gep_fu_94_p3;
reg   [6:0] orig2_addr_reg_468;
wire   [6:0] score1_addr_gep_fu_102_p3;
reg   [6:0] score1_addr_reg_473;
wire   [6:0] orig1_addr_gep_fu_110_p3;
reg   [6:0] orig1_addr_reg_478;
wire   [2:0] tmp_5_fu_203_p3;
reg   [2:0] tmp_5_reg_486;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_101;
wire   [0:0] tmp_fu_193_p2;
reg    ap_sig_bdd_109;
wire   [3:0] tmp_13_fu_255_p3;
reg   [3:0] tmp_13_reg_493;
wire   [7:0] tmp_14_fu_263_p3;
reg   [7:0] tmp_14_reg_498;
wire   [3:0] tmp_15_fu_271_p3;
reg   [3:0] tmp_15_reg_503;
wire   [1:0] tmp_22_fu_308_p1;
reg   [1:0] tmp_22_reg_508;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_126;
wire   [3:0] tmp_30_fu_347_p3;
reg   [3:0] tmp_30_reg_513;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_135;
wire   [7:0] tmp_31_fu_355_p3;
reg   [7:0] tmp_31_reg_518;
wire   [3:0] tmp_32_fu_363_p3;
reg   [3:0] tmp_32_reg_523;
wire   [7:0] score2_q0;
reg   [7:0] score2_load_reg_528;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_150;
wire   [19:0] orig2_q0;
reg   [19:0] max_orig_1_reg_533;
wire   [1:0] tmp_39_fu_400_p1;
reg   [1:0] tmp_39_reg_538;
wire   [19:0] max_orig_3_max_orig_fu_413_p3;
reg   [19:0] max_orig_3_max_orig_reg_543;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_163;
wire   [31:0] max_score_3_max_score_fu_420_p3;
reg   [31:0] max_score_3_max_score_reg_548;
wire   [19:0] i_1_fu_428_p2;
reg   [19:0] i_1_reg_554;
wire   [19:0] i_2_fu_435_p2;
reg   [19:0] i_2_reg_559;
wire   [7:0] score1_q0;
reg   [7:0] score1_load_reg_564;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_178;
wire   [19:0] max_orig_2_fu_449_p3;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_187;
wire   [31:0] max_score_2_fu_456_p3;
reg   [6:0] score1_address0;
reg    score1_ce0;
reg    score1_we0;
wire   [7:0] score1_d0;
reg   [6:0] score2_address0;
reg    score2_ce0;
reg    score2_we0;
wire   [7:0] score2_d0;
reg   [6:0] orig1_address0;
reg    orig1_ce0;
reg    orig1_we0;
wire   [19:0] orig1_d0;
wire   [19:0] orig1_q0;
reg   [6:0] orig2_address0;
reg    orig2_ce0;
reg    orig2_we0;
wire   [19:0] orig2_d0;
wire    grp_needlemanWunsch_doRow_fu_170_ap_start;
wire    grp_needlemanWunsch_doRow_fu_170_ap_done;
wire    grp_needlemanWunsch_doRow_fu_170_ap_idle;
wire    grp_needlemanWunsch_doRow_fu_170_ap_ready;
reg   [19:0] grp_needlemanWunsch_doRow_fu_170_i;
wire   [4:0] grp_needlemanWunsch_doRow_fu_170_read_r_address0;
wire    grp_needlemanWunsch_doRow_fu_170_read_r_ce0;
wire   [7:0] grp_needlemanWunsch_doRow_fu_170_read_r_q0;
reg   [1:0] grp_needlemanWunsch_doRow_fu_170_ref_genome;
wire   [6:0] grp_needlemanWunsch_doRow_fu_170_score_in_address0;
wire    grp_needlemanWunsch_doRow_fu_170_score_in_ce0;
reg   [7:0] grp_needlemanWunsch_doRow_fu_170_score_in_q0;
wire   [6:0] grp_needlemanWunsch_doRow_fu_170_score_out_address0;
wire    grp_needlemanWunsch_doRow_fu_170_score_out_ce0;
wire    grp_needlemanWunsch_doRow_fu_170_score_out_we0;
wire   [7:0] grp_needlemanWunsch_doRow_fu_170_score_out_d0;
wire   [6:0] grp_needlemanWunsch_doRow_fu_170_orig_in_address0;
wire    grp_needlemanWunsch_doRow_fu_170_orig_in_ce0;
reg   [19:0] grp_needlemanWunsch_doRow_fu_170_orig_in_q0;
wire   [6:0] grp_needlemanWunsch_doRow_fu_170_orig_out_address0;
wire    grp_needlemanWunsch_doRow_fu_170_orig_out_ce0;
wire    grp_needlemanWunsch_doRow_fu_170_orig_out_we0;
wire   [19:0] grp_needlemanWunsch_doRow_fu_170_orig_out_d0;
reg   [19:0] i_reg_134;
reg   [19:0] max_orig_reg_146;
reg   [31:0] max_score_reg_158;
reg    grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_267;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_275;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_282;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_293;
wire   [1:0] tmp_1_fu_199_p1;
wire  signed [2:0] tmp_7_cast_fu_211_p2;
wire   [2:0] tmp_9_fu_217_p2;
wire   [3:0] tmp_3_fu_229_p1;
wire   [3:0] tmp_6_fu_233_p1;
wire   [0:0] tmp_2_fu_223_p2;
wire   [3:0] tmp_10_fu_237_p2;
wire   [3:0] tmp_12_fu_249_p2;
reg   [7:0] grp_fu_183_p4;
wire   [3:0] tmp_11_fu_243_p2;
wire   [3:0] tmp_16_fu_279_p2;
wire   [7:0] tmp_17_fu_284_p1;
wire   [7:0] tmp_18_fu_287_p1;
wire   [7:0] tmp_19_fu_291_p2;
wire   [7:0] tmp_20_fu_296_p2;
wire   [7:0] tmp_21_fu_302_p2;
wire   [2:0] tmp_4_fu_312_p2;
wire   [3:0] tmp_24_fu_322_p1;
wire   [3:0] tmp_25_fu_325_p1;
wire   [0:0] tmp_23_fu_317_p2;
wire   [3:0] tmp_27_fu_329_p2;
wire   [3:0] tmp_29_fu_341_p2;
wire   [3:0] tmp_28_fu_335_p2;
wire   [3:0] tmp_33_fu_371_p2;
wire   [7:0] tmp_34_fu_376_p1;
wire   [7:0] tmp_35_fu_379_p1;
wire   [7:0] tmp_36_fu_383_p2;
wire   [7:0] tmp_37_fu_388_p2;
wire   [7:0] tmp_38_fu_394_p2;
wire  signed [31:0] max_score_1_fu_404_p1;
wire   [0:0] tmp_s_fu_407_p2;
wire  signed [31:0] max_score_3_fu_441_p1;
wire   [0:0] tmp_7_fu_444_p2;
reg   [11:0] ap_NS_fsm;


needlemanWunsch_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
needlemanWunsch_AXILiteS_s_axi_U(
    .AWVALID( s_axi_AXILiteS_AWVALID ),
    .AWREADY( s_axi_AXILiteS_AWREADY ),
    .AWADDR( s_axi_AXILiteS_AWADDR ),
    .WVALID( s_axi_AXILiteS_WVALID ),
    .WREADY( s_axi_AXILiteS_WREADY ),
    .WDATA( s_axi_AXILiteS_WDATA ),
    .WSTRB( s_axi_AXILiteS_WSTRB ),
    .ARVALID( s_axi_AXILiteS_ARVALID ),
    .ARREADY( s_axi_AXILiteS_ARREADY ),
    .ARADDR( s_axi_AXILiteS_ARADDR ),
    .RVALID( s_axi_AXILiteS_RVALID ),
    .RREADY( s_axi_AXILiteS_RREADY ),
    .RDATA( s_axi_AXILiteS_RDATA ),
    .RRESP( s_axi_AXILiteS_RRESP ),
    .BVALID( s_axi_AXILiteS_BVALID ),
    .BREADY( s_axi_AXILiteS_BREADY ),
    .BRESP( s_axi_AXILiteS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( needlemanWunsch_AXILiteS_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .ap_return( ap_return )
);

needlemanWunsch_score1 #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
score1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( score1_address0 ),
    .ce0( score1_ce0 ),
    .we0( score1_we0 ),
    .d0( score1_d0 ),
    .q0( score1_q0 )
);

needlemanWunsch_score1 #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
score2_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( score2_address0 ),
    .ce0( score2_ce0 ),
    .we0( score2_we0 ),
    .d0( score2_d0 ),
    .q0( score2_q0 )
);

needlemanWunsch_orig1 #(
    .DataWidth( 20 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
orig1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( orig1_address0 ),
    .ce0( orig1_ce0 ),
    .we0( orig1_we0 ),
    .d0( orig1_d0 ),
    .q0( orig1_q0 )
);

needlemanWunsch_orig1 #(
    .DataWidth( 20 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
orig2_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( orig2_address0 ),
    .ce0( orig2_ce0 ),
    .we0( orig2_we0 ),
    .d0( orig2_d0 ),
    .q0( orig2_q0 )
);

needlemanWunsch_doRow grp_needlemanWunsch_doRow_fu_170(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_needlemanWunsch_doRow_fu_170_ap_start ),
    .ap_done( grp_needlemanWunsch_doRow_fu_170_ap_done ),
    .ap_idle( grp_needlemanWunsch_doRow_fu_170_ap_idle ),
    .ap_ready( grp_needlemanWunsch_doRow_fu_170_ap_ready ),
    .i( grp_needlemanWunsch_doRow_fu_170_i ),
    .read_r_address0( grp_needlemanWunsch_doRow_fu_170_read_r_address0 ),
    .read_r_ce0( grp_needlemanWunsch_doRow_fu_170_read_r_ce0 ),
    .read_r_q0( grp_needlemanWunsch_doRow_fu_170_read_r_q0 ),
    .ref_genome( grp_needlemanWunsch_doRow_fu_170_ref_genome ),
    .score_in_address0( grp_needlemanWunsch_doRow_fu_170_score_in_address0 ),
    .score_in_ce0( grp_needlemanWunsch_doRow_fu_170_score_in_ce0 ),
    .score_in_q0( grp_needlemanWunsch_doRow_fu_170_score_in_q0 ),
    .score_out_address0( grp_needlemanWunsch_doRow_fu_170_score_out_address0 ),
    .score_out_ce0( grp_needlemanWunsch_doRow_fu_170_score_out_ce0 ),
    .score_out_we0( grp_needlemanWunsch_doRow_fu_170_score_out_we0 ),
    .score_out_d0( grp_needlemanWunsch_doRow_fu_170_score_out_d0 ),
    .orig_in_address0( grp_needlemanWunsch_doRow_fu_170_orig_in_address0 ),
    .orig_in_ce0( grp_needlemanWunsch_doRow_fu_170_orig_in_ce0 ),
    .orig_in_q0( grp_needlemanWunsch_doRow_fu_170_orig_in_q0 ),
    .orig_out_address0( grp_needlemanWunsch_doRow_fu_170_orig_out_address0 ),
    .orig_out_ce0( grp_needlemanWunsch_doRow_fu_170_orig_out_ce0 ),
    .orig_out_we0( grp_needlemanWunsch_doRow_fu_170_orig_out_we0 ),
    .orig_out_d0( grp_needlemanWunsch_doRow_fu_170_orig_out_d0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3))) begin
            grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_needlemanWunsch_doRow_fu_170_ap_ready)) begin
            grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        i_reg_134 <= i_2_reg_559;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_134 <= ap_const_lv20_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        max_orig_reg_146 <= max_orig_2_fu_449_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        max_orig_reg_146 <= ap_const_lv20_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        max_score_reg_158 <= max_score_2_fu_456_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        max_score_reg_158 <= ap_const_lv32_FFFFFF9C;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        i_1_reg_554 <= i_1_fu_428_p2;
        i_2_reg_559 <= i_2_fu_435_p2;
        max_orig_3_max_orig_reg_543 <= max_orig_3_max_orig_fu_413_p3;
        max_score_3_max_score_reg_548 <= max_score_3_max_score_fu_420_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        max_orig_1_reg_533 <= orig2_q0;
        score2_load_reg_528 <= score2_q0;
        tmp_39_reg_538 <= tmp_39_fu_400_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        score1_load_reg_564 <= score1_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109)) begin
        tmp_13_reg_493[3 : 1] <= tmp_13_fu_255_p3[3 : 1];
        tmp_14_reg_498 <= tmp_14_fu_263_p3;
        tmp_15_reg_503 <= tmp_15_fu_271_p3;
        tmp_5_reg_486[2 : 1] <= tmp_5_fu_203_p3[2 : 1];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        tmp_22_reg_508 <= tmp_22_fu_308_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ref_genome_TVALID == ap_const_logic_0))) begin
        tmp_30_reg_513[3 : 1] <= tmp_30_fu_347_p3[3 : 1];
        tmp_31_reg_518 <= tmp_31_fu_355_p3;
        tmp_32_reg_523 <= tmp_32_fu_363_p3;
    end
end

/// ap_done assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or tmp_fu_193_p2 or ap_sig_bdd_109)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or tmp_fu_193_p2 or ap_sig_bdd_109)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_293)
begin
    if (ap_sig_bdd_293) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_178)
begin
    if (ap_sig_bdd_178) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_187)
begin
    if (ap_sig_bdd_187) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_53)
begin
    if (ap_sig_bdd_53) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_101)
begin
    if (ap_sig_bdd_101) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_126)
begin
    if (ap_sig_bdd_126) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_267)
begin
    if (ap_sig_bdd_267) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_275)
begin
    if (ap_sig_bdd_275) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_135)
begin
    if (ap_sig_bdd_135) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_150)
begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_163)
begin
    if (ap_sig_bdd_163) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_282)
begin
    if (ap_sig_bdd_282) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// grp_needlemanWunsch_doRow_fu_170_i assign process. ///
always @ (i_1_reg_554 or i_reg_134 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        grp_needlemanWunsch_doRow_fu_170_i = i_1_reg_554;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_needlemanWunsch_doRow_fu_170_i = i_reg_134;
    end else begin
        grp_needlemanWunsch_doRow_fu_170_i = 'bx;
    end
end

/// grp_needlemanWunsch_doRow_fu_170_orig_in_q0 assign process. ///
always @ (orig2_q0 or orig1_q0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        grp_needlemanWunsch_doRow_fu_170_orig_in_q0 = orig2_q0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_needlemanWunsch_doRow_fu_170_orig_in_q0 = orig1_q0;
    end else begin
        grp_needlemanWunsch_doRow_fu_170_orig_in_q0 = 'bx;
    end
end

/// grp_needlemanWunsch_doRow_fu_170_ref_genome assign process. ///
always @ (tmp_22_reg_508 or tmp_39_reg_538 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        grp_needlemanWunsch_doRow_fu_170_ref_genome = tmp_39_reg_538;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_needlemanWunsch_doRow_fu_170_ref_genome = tmp_22_reg_508;
    end else begin
        grp_needlemanWunsch_doRow_fu_170_ref_genome = 'bx;
    end
end

/// grp_needlemanWunsch_doRow_fu_170_score_in_q0 assign process. ///
always @ (score2_q0 or score1_q0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        grp_needlemanWunsch_doRow_fu_170_score_in_q0 = score2_q0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_needlemanWunsch_doRow_fu_170_score_in_q0 = score1_q0;
    end else begin
        grp_needlemanWunsch_doRow_fu_170_score_in_q0 = 'bx;
    end
end

/// orig1_address0 assign process. ///
always @ (orig1_addr_reg_478 or ap_sig_cseq_ST_st11_fsm_10 or grp_needlemanWunsch_doRow_fu_170_orig_in_address0 or grp_needlemanWunsch_doRow_fu_170_orig_out_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        orig1_address0 = orig1_addr_reg_478;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        orig1_address0 = grp_needlemanWunsch_doRow_fu_170_orig_out_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        orig1_address0 = grp_needlemanWunsch_doRow_fu_170_orig_in_address0;
    end else begin
        orig1_address0 = 'bx;
    end
end

/// orig1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st11_fsm_10 or grp_needlemanWunsch_doRow_fu_170_orig_in_ce0 or grp_needlemanWunsch_doRow_fu_170_orig_out_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        orig1_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        orig1_ce0 = grp_needlemanWunsch_doRow_fu_170_orig_out_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        orig1_ce0 = grp_needlemanWunsch_doRow_fu_170_orig_in_ce0;
    end else begin
        orig1_ce0 = ap_const_logic_0;
    end
end

/// orig1_we0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_orig_out_we0 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        orig1_we0 = grp_needlemanWunsch_doRow_fu_170_orig_out_we0;
    end else begin
        orig1_we0 = ap_const_logic_0;
    end
end

/// orig2_address0 assign process. ///
always @ (orig2_addr_reg_468 or ap_sig_cseq_ST_st6_fsm_5 or grp_needlemanWunsch_doRow_fu_170_orig_in_address0 or grp_needlemanWunsch_doRow_fu_170_orig_out_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        orig2_address0 = orig2_addr_reg_468;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        orig2_address0 = grp_needlemanWunsch_doRow_fu_170_orig_out_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        orig2_address0 = grp_needlemanWunsch_doRow_fu_170_orig_in_address0;
    end else begin
        orig2_address0 = 'bx;
    end
end

/// orig2_ce0 assign process. ///
always @ (ref_genome_TVALID or ap_sig_cseq_ST_st6_fsm_5 or grp_needlemanWunsch_doRow_fu_170_orig_in_ce0 or grp_needlemanWunsch_doRow_fu_170_orig_out_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ref_genome_TVALID == ap_const_logic_0))) begin
        orig2_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        orig2_ce0 = grp_needlemanWunsch_doRow_fu_170_orig_out_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        orig2_ce0 = grp_needlemanWunsch_doRow_fu_170_orig_in_ce0;
    end else begin
        orig2_ce0 = ap_const_logic_0;
    end
end

/// orig2_we0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_orig_out_we0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        orig2_we0 = grp_needlemanWunsch_doRow_fu_170_orig_out_we0;
    end else begin
        orig2_we0 = ap_const_logic_0;
    end
end

/// read_r_ce0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_read_r_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        read_r_ce0 = grp_needlemanWunsch_doRow_fu_170_read_r_ce0;
    end else begin
        read_r_ce0 = ap_const_logic_0;
    end
end

/// ref_genome_TREADY assign process. ///
always @ (ref_genome_TVALID or ap_sig_cseq_ST_st2_fsm_1 or tmp_fu_193_p2 or ap_sig_bdd_109 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109) | ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ref_genome_TVALID == ap_const_logic_0)))) begin
        ref_genome_TREADY = ap_const_logic_1;
    end else begin
        ref_genome_TREADY = ap_const_logic_0;
    end
end

/// score1_address0 assign process. ///
always @ (score1_addr_reg_473 or grp_needlemanWunsch_doRow_fu_170_score_in_address0 or grp_needlemanWunsch_doRow_fu_170_score_out_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        score1_address0 = score1_addr_reg_473;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        score1_address0 = grp_needlemanWunsch_doRow_fu_170_score_out_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        score1_address0 = grp_needlemanWunsch_doRow_fu_170_score_in_address0;
    end else begin
        score1_address0 = 'bx;
    end
end

/// score1_ce0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_score_in_ce0 or grp_needlemanWunsch_doRow_fu_170_score_out_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        score1_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        score1_ce0 = grp_needlemanWunsch_doRow_fu_170_score_out_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        score1_ce0 = grp_needlemanWunsch_doRow_fu_170_score_in_ce0;
    end else begin
        score1_ce0 = ap_const_logic_0;
    end
end

/// score1_we0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_score_out_we0 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        score1_we0 = grp_needlemanWunsch_doRow_fu_170_score_out_we0;
    end else begin
        score1_we0 = ap_const_logic_0;
    end
end

/// score2_address0 assign process. ///
always @ (score2_addr_reg_463 or ap_sig_cseq_ST_st6_fsm_5 or grp_needlemanWunsch_doRow_fu_170_score_in_address0 or grp_needlemanWunsch_doRow_fu_170_score_out_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        score2_address0 = score2_addr_reg_463;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        score2_address0 = grp_needlemanWunsch_doRow_fu_170_score_out_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        score2_address0 = grp_needlemanWunsch_doRow_fu_170_score_in_address0;
    end else begin
        score2_address0 = 'bx;
    end
end

/// score2_ce0 assign process. ///
always @ (ref_genome_TVALID or ap_sig_cseq_ST_st6_fsm_5 or grp_needlemanWunsch_doRow_fu_170_score_in_ce0 or grp_needlemanWunsch_doRow_fu_170_score_out_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st9_fsm_8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ref_genome_TVALID == ap_const_logic_0))) begin
        score2_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        score2_ce0 = grp_needlemanWunsch_doRow_fu_170_score_out_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        score2_ce0 = grp_needlemanWunsch_doRow_fu_170_score_in_ce0;
    end else begin
        score2_ce0 = ap_const_logic_0;
    end
end

/// score2_we0 assign process. ///
always @ (grp_needlemanWunsch_doRow_fu_170_score_out_we0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        score2_we0 = grp_needlemanWunsch_doRow_fu_170_score_out_we0;
    end else begin
        score2_we0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or ref_genome_TVALID or tmp_fu_193_p2 or ap_sig_bdd_109 or grp_needlemanWunsch_doRow_fu_170_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (((tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if ((~(tmp_fu_193_p2 == ap_const_lv1_0) & ~ap_sig_bdd_109)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_needlemanWunsch_doRow_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            if (~(ref_genome_TVALID == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (~(ap_const_logic_0 == grp_needlemanWunsch_doRow_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = max_orig_reg_146;

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_101 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_101 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_109 assign process. ///
always @ (ref_genome_TVALID or tmp_fu_193_p2)
begin
    ap_sig_bdd_109 = ((ref_genome_TVALID == ap_const_logic_0) & ~(tmp_fu_193_p2 == ap_const_lv1_0));
end

/// ap_sig_bdd_126 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_126 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_135 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_135 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_150 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_163 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_163 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_178 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_178 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_187 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_187 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_267 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_267 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_275 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_275 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_282 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_282 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_293 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_293 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_53 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_53 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

integer ap_tvar_int_0;

always @ (ref_genome_TDATA) begin
    for (ap_tvar_int_0 = 8 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > ap_const_lv32_7 - ap_const_lv32_0) begin
            grp_fu_183_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            grp_fu_183_p4[ap_tvar_int_0] = ref_genome_TDATA[ap_const_lv32_7 - ap_tvar_int_0];
        end
    end
end


assign grp_needlemanWunsch_doRow_fu_170_ap_start = grp_needlemanWunsch_doRow_fu_170_ap_start_ap_start_reg;
assign grp_needlemanWunsch_doRow_fu_170_read_r_q0 = read_r_q0;
assign i_1_fu_428_p2 = (ap_const_lv20_1 + i_reg_134);
assign i_2_fu_435_p2 = (ap_const_lv20_2 + i_reg_134);
assign max_orig_2_fu_449_p3 = ((tmp_7_fu_444_p2[0:0]===1'b1)? orig1_q0: max_orig_3_max_orig_reg_543);
assign max_orig_3_max_orig_fu_413_p3 = ((tmp_s_fu_407_p2[0:0]===1'b1)? max_orig_1_reg_533: max_orig_reg_146);
assign max_score_1_fu_404_p1 = $signed(score2_load_reg_528);
assign max_score_2_fu_456_p3 = ((tmp_7_fu_444_p2[0:0]===1'b1)? max_score_3_fu_441_p1: max_score_3_max_score_reg_548);
assign max_score_3_fu_441_p1 = $signed(score1_load_reg_564);
assign max_score_3_max_score_fu_420_p3 = ((tmp_s_fu_407_p2[0:0]===1'b1)? max_score_1_fu_404_p1: max_score_reg_158);
assign needlemanWunsch_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
assign orig1_addr_gep_fu_110_p3 = ap_const_lv64_63;
assign orig1_d0 = grp_needlemanWunsch_doRow_fu_170_orig_out_d0;
assign orig2_addr_gep_fu_94_p3 = ap_const_lv64_63;
assign orig2_d0 = grp_needlemanWunsch_doRow_fu_170_orig_out_d0;
assign read_r_address0 = grp_needlemanWunsch_doRow_fu_170_read_r_address0;
assign score1_addr_gep_fu_102_p3 = ap_const_lv64_63;
assign score1_d0 = grp_needlemanWunsch_doRow_fu_170_score_out_d0;
assign score2_addr_gep_fu_86_p3 = ap_const_lv64_63;
assign score2_d0 = grp_needlemanWunsch_doRow_fu_170_score_out_d0;
assign tmp_10_fu_237_p2 = (tmp_3_fu_229_p1 - tmp_6_fu_233_p1);
assign tmp_11_fu_243_p2 = (tmp_3_fu_229_p1 ^ ap_const_lv4_7);
assign tmp_12_fu_249_p2 = (tmp_6_fu_233_p1 - tmp_3_fu_229_p1);
assign tmp_13_fu_255_p3 = ((tmp_2_fu_223_p2[0:0]===1'b1)? tmp_10_fu_237_p2: tmp_12_fu_249_p2);
assign tmp_14_fu_263_p3 = ((tmp_2_fu_223_p2[0:0]===1'b1)? grp_fu_183_p4: ref_genome_TDATA);
assign tmp_15_fu_271_p3 = ((tmp_2_fu_223_p2[0:0]===1'b1)? tmp_11_fu_243_p2: tmp_3_fu_229_p1);
assign tmp_16_fu_279_p2 = (ap_const_lv4_7 - tmp_13_reg_493);
assign tmp_17_fu_284_p1 = tmp_15_reg_503;
assign tmp_18_fu_287_p1 = tmp_16_fu_279_p2;
assign tmp_19_fu_291_p2 = tmp_14_reg_498 >> tmp_17_fu_284_p1;
assign tmp_1_fu_199_p1 = i_reg_134[1:0];
assign tmp_20_fu_296_p2 = ap_const_lv8_FF >> tmp_18_fu_287_p1;
assign tmp_21_fu_302_p2 = (tmp_19_fu_291_p2 & tmp_20_fu_296_p2);
assign tmp_22_fu_308_p1 = tmp_21_fu_302_p2[1:0];
assign tmp_23_fu_317_p2 = (tmp_5_reg_486 > tmp_4_fu_312_p2? 1'b1: 1'b0);
assign tmp_24_fu_322_p1 = tmp_5_reg_486;
assign tmp_25_fu_325_p1 = tmp_4_fu_312_p2;
assign tmp_27_fu_329_p2 = (tmp_24_fu_322_p1 - tmp_25_fu_325_p1);
assign tmp_28_fu_335_p2 = (tmp_24_fu_322_p1 ^ ap_const_lv4_7);
assign tmp_29_fu_341_p2 = (tmp_25_fu_325_p1 - tmp_24_fu_322_p1);
assign tmp_2_fu_223_p2 = (tmp_7_cast_fu_211_p2 > tmp_9_fu_217_p2? 1'b1: 1'b0);
assign tmp_30_fu_347_p3 = ((tmp_23_fu_317_p2[0:0]===1'b1)? tmp_27_fu_329_p2: tmp_29_fu_341_p2);
assign tmp_31_fu_355_p3 = ((tmp_23_fu_317_p2[0:0]===1'b1)? grp_fu_183_p4: ref_genome_TDATA);
assign tmp_32_fu_363_p3 = ((tmp_23_fu_317_p2[0:0]===1'b1)? tmp_28_fu_335_p2: tmp_24_fu_322_p1);
assign tmp_33_fu_371_p2 = (ap_const_lv4_7 - tmp_30_reg_513);
assign tmp_34_fu_376_p1 = tmp_32_reg_523;
assign tmp_35_fu_379_p1 = tmp_33_fu_371_p2;
assign tmp_36_fu_383_p2 = tmp_31_reg_518 >> tmp_34_fu_376_p1;
assign tmp_37_fu_388_p2 = ap_const_lv8_FF >> tmp_35_fu_379_p1;
assign tmp_38_fu_394_p2 = (tmp_36_fu_383_p2 & tmp_37_fu_388_p2);
assign tmp_39_fu_400_p1 = tmp_38_fu_394_p2[1:0];
assign tmp_3_fu_229_p1 = $unsigned(tmp_7_cast_fu_211_p2);
assign tmp_4_fu_312_p2 = (tmp_5_reg_486 | ap_const_lv3_1);
assign tmp_5_fu_203_p3 = {{tmp_1_fu_199_p1}, {ap_const_lv1_0}};
assign tmp_6_fu_233_p1 = tmp_9_fu_217_p2;
assign tmp_7_cast_fu_211_p2 = ($signed(ap_const_lv3_6) + $signed(tmp_5_fu_203_p3));
assign tmp_7_fu_444_p2 = ($signed(max_score_3_fu_441_p1) > $signed(max_score_3_max_score_reg_548)? 1'b1: 1'b0);
assign tmp_9_fu_217_p2 = (tmp_7_cast_fu_211_p2 | ap_const_lv3_1);
assign tmp_fu_193_p2 = (i_reg_134 < ap_const_lv20_F4241? 1'b1: 1'b0);
assign tmp_s_fu_407_p2 = ($signed(max_score_1_fu_404_p1) > $signed(max_score_reg_158)? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    score2_addr_reg_463[6:0] <= 7'b1100011;
    orig2_addr_reg_468[6:0] <= 7'b1100011;
    score1_addr_reg_473[6:0] <= 7'b1100011;
    orig1_addr_reg_478[6:0] <= 7'b1100011;
    tmp_5_reg_486[0] <= 1'b0;
    tmp_13_reg_493[0] <= 1'b1;
    tmp_30_reg_513[0] <= 1'b1;
end



endmodule //needlemanWunsch

