/* Definition for CPU ID */
#define XPAR_CPU_ID 0

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Definitions for driver AXIDMA */
#define XPAR_XAXIDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_DMA_0 */
#define XPAR_AXI_DMA_0_DEVICE_ID 0
#define XPAR_AXI_DMA_0_BASEADDR 0x40400000
#define XPAR_AXI_DMA_0_HIGHADDR 0x4040FFFF
#define XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE 0
#define XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE 0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S 1
#define XPAR_AXI_DMA_0_INCLUDE_S2MM 0
#define XPAR_AXI_DMA_0_M_AXI_MM2S_DATA_WIDTH 64
#define XPAR_AXI_DMA_0_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXI_DMA_0_INCLUDE_SG 0
#define XPAR_AXI_DMA_0_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS 1
#define XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS 1
#define XPAR_AXI_DMA_0_MM2S_BURST_SIZE 8
#define XPAR_AXI_DMA_0_S2MM_BURST_SIZE 16
#define XPAR_AXI_DMA_0_MICRO_DMA 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_DMA_0 */
#define XPAR_AXIDMA_0_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID
#define XPAR_AXIDMA_0_BASEADDR 0x40400000
#define XPAR_AXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXIDMA_0_INCLUDE_MM2S 1
#define XPAR_AXIDMA_0_INCLUDE_MM2S_DRE 0
#define XPAR_AXIDMA_0_M_AXI_MM2S_DATA_WIDTH 64
#define XPAR_AXIDMA_0_INCLUDE_S2MM 0
#define XPAR_AXIDMA_0_INCLUDE_S2MM_DRE 0
#define XPAR_AXIDMA_0_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXIDMA_0_INCLUDE_SG 0
#define XPAR_AXIDMA_0_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXIDMA_0_NUM_MM2S_CHANNELS 1
#define XPAR_AXIDMA_0_NUM_S2MM_CHANNELS 1
#define XPAR_AXIDMA_0_MM2S_BURST_SIZE 8
#define XPAR_AXIDMA_0_S2MM_BURST_SIZE 16
#define XPAR_AXIDMA_0_MICRO_DMA 0


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 51

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_0_ECC 0
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x40000000
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x40000FFF
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_AXI_BRAM_CTRL_1_DEVICE_ID 1
#define XPAR_AXI_BRAM_CTRL_1_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_1_ECC 0
#define XPAR_AXI_BRAM_CTRL_1_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_1_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_1_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_1_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0x42000000
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_HIGHADDR 0x42000FFF
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_10 */
#define XPAR_AXI_BRAM_CTRL_10_DEVICE_ID 2
#define XPAR_AXI_BRAM_CTRL_10_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_10_ECC 0
#define XPAR_AXI_BRAM_CTRL_10_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_10_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_10_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_10_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_10_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_10_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_10_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_10_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_BASEADDR 0x54000000
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_HIGHADDR 0x54000FFF
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_11 */
#define XPAR_AXI_BRAM_CTRL_11_DEVICE_ID 3
#define XPAR_AXI_BRAM_CTRL_11_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_11_ECC 0
#define XPAR_AXI_BRAM_CTRL_11_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_11_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_11_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_11_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_11_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_11_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_11_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_11_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_BASEADDR 0x56000000
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_HIGHADDR 0x56000FFF
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_12 */
#define XPAR_AXI_BRAM_CTRL_12_DEVICE_ID 4
#define XPAR_AXI_BRAM_CTRL_12_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_12_ECC 0
#define XPAR_AXI_BRAM_CTRL_12_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_12_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_12_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_12_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_12_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_12_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_12_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_12_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_BASEADDR 0x58000000
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_HIGHADDR 0x58000FFF
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_13 */
#define XPAR_AXI_BRAM_CTRL_13_DEVICE_ID 5
#define XPAR_AXI_BRAM_CTRL_13_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_13_ECC 0
#define XPAR_AXI_BRAM_CTRL_13_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_13_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_13_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_13_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_13_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_13_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_13_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_13_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_BASEADDR 0x5A000000
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_HIGHADDR 0x5A000FFF
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_14 */
#define XPAR_AXI_BRAM_CTRL_14_DEVICE_ID 6
#define XPAR_AXI_BRAM_CTRL_14_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_14_ECC 0
#define XPAR_AXI_BRAM_CTRL_14_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_14_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_14_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_14_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_14_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_14_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_14_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_14_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_BASEADDR 0x5C000000
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_HIGHADDR 0x5C000FFF
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_15 */
#define XPAR_AXI_BRAM_CTRL_15_DEVICE_ID 7
#define XPAR_AXI_BRAM_CTRL_15_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_15_ECC 0
#define XPAR_AXI_BRAM_CTRL_15_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_15_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_15_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_15_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_15_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_15_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_15_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_15_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_BASEADDR 0x5E000000
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_HIGHADDR 0x5E000FFF
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_16 */
#define XPAR_AXI_BRAM_CTRL_16_DEVICE_ID 8
#define XPAR_AXI_BRAM_CTRL_16_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_16_ECC 0
#define XPAR_AXI_BRAM_CTRL_16_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_16_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_16_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_16_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_16_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_16_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_16_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_16_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_BASEADDR 0x60000000
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_HIGHADDR 0x60000FFF
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_17 */
#define XPAR_AXI_BRAM_CTRL_17_DEVICE_ID 9
#define XPAR_AXI_BRAM_CTRL_17_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_17_ECC 0
#define XPAR_AXI_BRAM_CTRL_17_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_17_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_17_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_17_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_17_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_17_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_17_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_17_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_BASEADDR 0x62000000
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_HIGHADDR 0x62000FFF
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_18 */
#define XPAR_AXI_BRAM_CTRL_18_DEVICE_ID 10
#define XPAR_AXI_BRAM_CTRL_18_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_18_ECC 0
#define XPAR_AXI_BRAM_CTRL_18_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_18_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_18_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_18_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_18_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_18_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_18_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_18_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_BASEADDR 0x64000000
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_HIGHADDR 0x64000FFF
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_19 */
#define XPAR_AXI_BRAM_CTRL_19_DEVICE_ID 11
#define XPAR_AXI_BRAM_CTRL_19_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_19_ECC 0
#define XPAR_AXI_BRAM_CTRL_19_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_19_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_19_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_19_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_19_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_19_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_19_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_19_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_BASEADDR 0x66000000
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_HIGHADDR 0x66000FFF
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_AXI_BRAM_CTRL_2_DEVICE_ID 12
#define XPAR_AXI_BRAM_CTRL_2_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_2_ECC 0
#define XPAR_AXI_BRAM_CTRL_2_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_2_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_2_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_2_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_2_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_2_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_BASEADDR 0x44000000
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_HIGHADDR 0x44000FFF
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_20 */
#define XPAR_AXI_BRAM_CTRL_20_DEVICE_ID 13
#define XPAR_AXI_BRAM_CTRL_20_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_20_ECC 0
#define XPAR_AXI_BRAM_CTRL_20_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_20_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_20_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_20_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_20_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_20_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_20_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_20_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_BASEADDR 0x68000000
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_HIGHADDR 0x68000FFF
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_21 */
#define XPAR_AXI_BRAM_CTRL_21_DEVICE_ID 14
#define XPAR_AXI_BRAM_CTRL_21_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_21_ECC 0
#define XPAR_AXI_BRAM_CTRL_21_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_21_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_21_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_21_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_21_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_21_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_21_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_21_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_BASEADDR 0x6A000000
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_HIGHADDR 0x6A000FFF
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_22 */
#define XPAR_AXI_BRAM_CTRL_22_DEVICE_ID 15
#define XPAR_AXI_BRAM_CTRL_22_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_22_ECC 0
#define XPAR_AXI_BRAM_CTRL_22_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_22_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_22_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_22_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_22_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_22_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_22_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_22_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_22_S_AXI_BASEADDR 0x6C000000
#define XPAR_AXI_BRAM_CTRL_22_S_AXI_HIGHADDR 0x6C000FFF
#define XPAR_AXI_BRAM_CTRL_22_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_22_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_23 */
#define XPAR_AXI_BRAM_CTRL_23_DEVICE_ID 16
#define XPAR_AXI_BRAM_CTRL_23_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_23_ECC 0
#define XPAR_AXI_BRAM_CTRL_23_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_23_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_23_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_23_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_23_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_23_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_23_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_23_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_23_S_AXI_BASEADDR 0x6E000000
#define XPAR_AXI_BRAM_CTRL_23_S_AXI_HIGHADDR 0x6E000FFF
#define XPAR_AXI_BRAM_CTRL_23_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_23_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_24 */
#define XPAR_AXI_BRAM_CTRL_24_DEVICE_ID 17
#define XPAR_AXI_BRAM_CTRL_24_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_24_ECC 0
#define XPAR_AXI_BRAM_CTRL_24_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_24_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_24_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_24_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_24_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_24_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_24_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_24_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_24_S_AXI_BASEADDR 0x70000000
#define XPAR_AXI_BRAM_CTRL_24_S_AXI_HIGHADDR 0x70000FFF
#define XPAR_AXI_BRAM_CTRL_24_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_24_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_25 */
#define XPAR_AXI_BRAM_CTRL_25_DEVICE_ID 18
#define XPAR_AXI_BRAM_CTRL_25_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_25_ECC 0
#define XPAR_AXI_BRAM_CTRL_25_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_25_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_25_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_25_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_25_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_25_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_25_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_25_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_25_S_AXI_BASEADDR 0x72000000
#define XPAR_AXI_BRAM_CTRL_25_S_AXI_HIGHADDR 0x72000FFF
#define XPAR_AXI_BRAM_CTRL_25_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_25_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_26 */
#define XPAR_AXI_BRAM_CTRL_26_DEVICE_ID 19
#define XPAR_AXI_BRAM_CTRL_26_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_26_ECC 0
#define XPAR_AXI_BRAM_CTRL_26_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_26_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_26_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_26_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_26_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_26_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_26_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_26_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_26_S_AXI_BASEADDR 0x74000000
#define XPAR_AXI_BRAM_CTRL_26_S_AXI_HIGHADDR 0x74000FFF
#define XPAR_AXI_BRAM_CTRL_26_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_26_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_27 */
#define XPAR_AXI_BRAM_CTRL_27_DEVICE_ID 20
#define XPAR_AXI_BRAM_CTRL_27_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_27_ECC 0
#define XPAR_AXI_BRAM_CTRL_27_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_27_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_27_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_27_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_27_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_27_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_27_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_27_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_27_S_AXI_BASEADDR 0x76000000
#define XPAR_AXI_BRAM_CTRL_27_S_AXI_HIGHADDR 0x76000FFF
#define XPAR_AXI_BRAM_CTRL_27_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_27_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_28 */
#define XPAR_AXI_BRAM_CTRL_28_DEVICE_ID 21
#define XPAR_AXI_BRAM_CTRL_28_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_28_ECC 0
#define XPAR_AXI_BRAM_CTRL_28_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_28_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_28_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_28_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_28_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_28_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_28_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_28_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_28_S_AXI_BASEADDR 0x78000000
#define XPAR_AXI_BRAM_CTRL_28_S_AXI_HIGHADDR 0x78000FFF
#define XPAR_AXI_BRAM_CTRL_28_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_28_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_29 */
#define XPAR_AXI_BRAM_CTRL_29_DEVICE_ID 22
#define XPAR_AXI_BRAM_CTRL_29_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_29_ECC 0
#define XPAR_AXI_BRAM_CTRL_29_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_29_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_29_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_29_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_29_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_29_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_29_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_29_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_29_S_AXI_BASEADDR 0x7A000000
#define XPAR_AXI_BRAM_CTRL_29_S_AXI_HIGHADDR 0x7A000FFF
#define XPAR_AXI_BRAM_CTRL_29_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_29_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_AXI_BRAM_CTRL_3_DEVICE_ID 23
#define XPAR_AXI_BRAM_CTRL_3_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_3_ECC 0
#define XPAR_AXI_BRAM_CTRL_3_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_3_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_3_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_3_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_3_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_3_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_BASEADDR 0x46000000
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_HIGHADDR 0x46000FFF
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_30 */
#define XPAR_AXI_BRAM_CTRL_30_DEVICE_ID 24
#define XPAR_AXI_BRAM_CTRL_30_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_30_ECC 0
#define XPAR_AXI_BRAM_CTRL_30_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_30_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_30_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_30_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_30_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_30_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_30_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_30_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_30_S_AXI_BASEADDR 0x7C000000
#define XPAR_AXI_BRAM_CTRL_30_S_AXI_HIGHADDR 0x7C000FFF
#define XPAR_AXI_BRAM_CTRL_30_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_30_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_31 */
#define XPAR_AXI_BRAM_CTRL_31_DEVICE_ID 25
#define XPAR_AXI_BRAM_CTRL_31_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_31_ECC 0
#define XPAR_AXI_BRAM_CTRL_31_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_31_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_31_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_31_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_31_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_31_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_31_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_31_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_31_S_AXI_BASEADDR 0x7E000000
#define XPAR_AXI_BRAM_CTRL_31_S_AXI_HIGHADDR 0x7E000FFF
#define XPAR_AXI_BRAM_CTRL_31_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_31_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_32 */
#define XPAR_AXI_BRAM_CTRL_32_DEVICE_ID 26
#define XPAR_AXI_BRAM_CTRL_32_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_32_ECC 0
#define XPAR_AXI_BRAM_CTRL_32_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_32_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_32_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_32_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_32_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_32_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_32_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_32_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_32_S_AXI_BASEADDR 0x7E002000
#define XPAR_AXI_BRAM_CTRL_32_S_AXI_HIGHADDR 0x7E002FFF
#define XPAR_AXI_BRAM_CTRL_32_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_32_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_33 */
#define XPAR_AXI_BRAM_CTRL_33_DEVICE_ID 27
#define XPAR_AXI_BRAM_CTRL_33_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_33_ECC 0
#define XPAR_AXI_BRAM_CTRL_33_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_33_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_33_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_33_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_33_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_33_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_33_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_33_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_33_S_AXI_BASEADDR 0x7E004000
#define XPAR_AXI_BRAM_CTRL_33_S_AXI_HIGHADDR 0x7E004FFF
#define XPAR_AXI_BRAM_CTRL_33_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_33_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_34 */
#define XPAR_AXI_BRAM_CTRL_34_DEVICE_ID 28
#define XPAR_AXI_BRAM_CTRL_34_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_34_ECC 0
#define XPAR_AXI_BRAM_CTRL_34_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_34_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_34_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_34_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_34_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_34_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_34_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_34_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_34_S_AXI_BASEADDR 0x7E006000
#define XPAR_AXI_BRAM_CTRL_34_S_AXI_HIGHADDR 0x7E006FFF
#define XPAR_AXI_BRAM_CTRL_34_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_34_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_35 */
#define XPAR_AXI_BRAM_CTRL_35_DEVICE_ID 29
#define XPAR_AXI_BRAM_CTRL_35_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_35_ECC 0
#define XPAR_AXI_BRAM_CTRL_35_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_35_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_35_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_35_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_35_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_35_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_35_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_35_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_35_S_AXI_BASEADDR 0x7E008000
#define XPAR_AXI_BRAM_CTRL_35_S_AXI_HIGHADDR 0x7E008FFF
#define XPAR_AXI_BRAM_CTRL_35_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_35_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_36 */
#define XPAR_AXI_BRAM_CTRL_36_DEVICE_ID 30
#define XPAR_AXI_BRAM_CTRL_36_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_36_ECC 0
#define XPAR_AXI_BRAM_CTRL_36_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_36_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_36_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_36_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_36_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_36_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_36_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_36_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_36_S_AXI_BASEADDR 0x7E00A000
#define XPAR_AXI_BRAM_CTRL_36_S_AXI_HIGHADDR 0x7E00AFFF
#define XPAR_AXI_BRAM_CTRL_36_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_36_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_37 */
#define XPAR_AXI_BRAM_CTRL_37_DEVICE_ID 31
#define XPAR_AXI_BRAM_CTRL_37_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_37_ECC 0
#define XPAR_AXI_BRAM_CTRL_37_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_37_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_37_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_37_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_37_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_37_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_37_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_37_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_37_S_AXI_BASEADDR 0x7E00C000
#define XPAR_AXI_BRAM_CTRL_37_S_AXI_HIGHADDR 0x7E00CFFF
#define XPAR_AXI_BRAM_CTRL_37_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_37_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_38 */
#define XPAR_AXI_BRAM_CTRL_38_DEVICE_ID 32
#define XPAR_AXI_BRAM_CTRL_38_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_38_ECC 0
#define XPAR_AXI_BRAM_CTRL_38_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_38_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_38_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_38_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_38_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_38_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_38_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_38_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_38_S_AXI_BASEADDR 0x7E00E000
#define XPAR_AXI_BRAM_CTRL_38_S_AXI_HIGHADDR 0x7E00EFFF
#define XPAR_AXI_BRAM_CTRL_38_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_38_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_39 */
#define XPAR_AXI_BRAM_CTRL_39_DEVICE_ID 33
#define XPAR_AXI_BRAM_CTRL_39_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_39_ECC 0
#define XPAR_AXI_BRAM_CTRL_39_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_39_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_39_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_39_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_39_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_39_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_39_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_39_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_39_S_AXI_BASEADDR 0x7E010000
#define XPAR_AXI_BRAM_CTRL_39_S_AXI_HIGHADDR 0x7E010FFF
#define XPAR_AXI_BRAM_CTRL_39_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_39_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_AXI_BRAM_CTRL_4_DEVICE_ID 34
#define XPAR_AXI_BRAM_CTRL_4_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_4_ECC 0
#define XPAR_AXI_BRAM_CTRL_4_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_4_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_4_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_4_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_4_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_4_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_BASEADDR 0x48000000
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_HIGHADDR 0x48000FFF
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_40 */
#define XPAR_AXI_BRAM_CTRL_40_DEVICE_ID 35
#define XPAR_AXI_BRAM_CTRL_40_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_40_ECC 0
#define XPAR_AXI_BRAM_CTRL_40_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_40_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_40_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_40_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_40_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_40_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_40_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_40_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_40_S_AXI_BASEADDR 0x7E012000
#define XPAR_AXI_BRAM_CTRL_40_S_AXI_HIGHADDR 0x7E012FFF
#define XPAR_AXI_BRAM_CTRL_40_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_40_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_41 */
#define XPAR_AXI_BRAM_CTRL_41_DEVICE_ID 36
#define XPAR_AXI_BRAM_CTRL_41_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_41_ECC 0
#define XPAR_AXI_BRAM_CTRL_41_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_41_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_41_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_41_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_41_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_41_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_41_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_41_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_41_S_AXI_BASEADDR 0x7E014000
#define XPAR_AXI_BRAM_CTRL_41_S_AXI_HIGHADDR 0x7E014FFF
#define XPAR_AXI_BRAM_CTRL_41_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_41_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_42 */
#define XPAR_AXI_BRAM_CTRL_42_DEVICE_ID 37
#define XPAR_AXI_BRAM_CTRL_42_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_42_ECC 0
#define XPAR_AXI_BRAM_CTRL_42_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_42_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_42_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_42_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_42_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_42_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_42_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_42_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_42_S_AXI_BASEADDR 0x7E016000
#define XPAR_AXI_BRAM_CTRL_42_S_AXI_HIGHADDR 0x7E016FFF
#define XPAR_AXI_BRAM_CTRL_42_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_42_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_43 */
#define XPAR_AXI_BRAM_CTRL_43_DEVICE_ID 38
#define XPAR_AXI_BRAM_CTRL_43_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_43_ECC 0
#define XPAR_AXI_BRAM_CTRL_43_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_43_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_43_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_43_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_43_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_43_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_43_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_43_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_43_S_AXI_BASEADDR 0x7E018000
#define XPAR_AXI_BRAM_CTRL_43_S_AXI_HIGHADDR 0x7E018FFF
#define XPAR_AXI_BRAM_CTRL_43_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_43_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_44 */
#define XPAR_AXI_BRAM_CTRL_44_DEVICE_ID 39
#define XPAR_AXI_BRAM_CTRL_44_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_44_ECC 0
#define XPAR_AXI_BRAM_CTRL_44_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_44_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_44_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_44_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_44_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_44_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_44_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_44_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_44_S_AXI_BASEADDR 0x7E01A000
#define XPAR_AXI_BRAM_CTRL_44_S_AXI_HIGHADDR 0x7E01AFFF
#define XPAR_AXI_BRAM_CTRL_44_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_44_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_45 */
#define XPAR_AXI_BRAM_CTRL_45_DEVICE_ID 40
#define XPAR_AXI_BRAM_CTRL_45_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_45_ECC 0
#define XPAR_AXI_BRAM_CTRL_45_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_45_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_45_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_45_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_45_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_45_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_45_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_45_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_45_S_AXI_BASEADDR 0x7E01C000
#define XPAR_AXI_BRAM_CTRL_45_S_AXI_HIGHADDR 0x7E01CFFF
#define XPAR_AXI_BRAM_CTRL_45_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_45_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_46 */
#define XPAR_AXI_BRAM_CTRL_46_DEVICE_ID 41
#define XPAR_AXI_BRAM_CTRL_46_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_46_ECC 0
#define XPAR_AXI_BRAM_CTRL_46_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_46_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_46_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_46_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_46_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_46_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_46_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_46_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_46_S_AXI_BASEADDR 0x7E01E000
#define XPAR_AXI_BRAM_CTRL_46_S_AXI_HIGHADDR 0x7E01EFFF
#define XPAR_AXI_BRAM_CTRL_46_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_46_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_47 */
#define XPAR_AXI_BRAM_CTRL_47_DEVICE_ID 42
#define XPAR_AXI_BRAM_CTRL_47_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_47_ECC 0
#define XPAR_AXI_BRAM_CTRL_47_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_47_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_47_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_47_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_47_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_47_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_47_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_47_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_47_S_AXI_BASEADDR 0x7E020000
#define XPAR_AXI_BRAM_CTRL_47_S_AXI_HIGHADDR 0x7E020FFF
#define XPAR_AXI_BRAM_CTRL_47_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_47_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_48 */
#define XPAR_AXI_BRAM_CTRL_48_DEVICE_ID 43
#define XPAR_AXI_BRAM_CTRL_48_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_48_ECC 0
#define XPAR_AXI_BRAM_CTRL_48_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_48_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_48_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_48_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_48_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_48_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_48_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_48_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_48_S_AXI_BASEADDR 0x7E022000
#define XPAR_AXI_BRAM_CTRL_48_S_AXI_HIGHADDR 0x7E022FFF
#define XPAR_AXI_BRAM_CTRL_48_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_48_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_49 */
#define XPAR_AXI_BRAM_CTRL_49_DEVICE_ID 44
#define XPAR_AXI_BRAM_CTRL_49_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_49_ECC 0
#define XPAR_AXI_BRAM_CTRL_49_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_49_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_49_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_49_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_49_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_49_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_49_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_49_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_49_S_AXI_BASEADDR 0x7E024000
#define XPAR_AXI_BRAM_CTRL_49_S_AXI_HIGHADDR 0x7E024FFF
#define XPAR_AXI_BRAM_CTRL_49_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_49_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_AXI_BRAM_CTRL_5_DEVICE_ID 45
#define XPAR_AXI_BRAM_CTRL_5_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_5_ECC 0
#define XPAR_AXI_BRAM_CTRL_5_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_5_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_5_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_5_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_5_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_5_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_BASEADDR 0x4A000000
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_HIGHADDR 0x4A000FFF
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_AXI_BRAM_CTRL_6_DEVICE_ID 46
#define XPAR_AXI_BRAM_CTRL_6_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_6_ECC 0
#define XPAR_AXI_BRAM_CTRL_6_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_6_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_6_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_6_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_6_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_6_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_BASEADDR 0x4C000000
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_HIGHADDR 0x4C000FFF
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_AXI_BRAM_CTRL_7_DEVICE_ID 47
#define XPAR_AXI_BRAM_CTRL_7_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_7_ECC 0
#define XPAR_AXI_BRAM_CTRL_7_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_7_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_7_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_7_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_7_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_7_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_BASEADDR 0x4E000000
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_HIGHADDR 0x4E000FFF
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_8 */
#define XPAR_AXI_BRAM_CTRL_8_DEVICE_ID 48
#define XPAR_AXI_BRAM_CTRL_8_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_8_ECC 0
#define XPAR_AXI_BRAM_CTRL_8_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_8_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_8_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_8_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_8_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_8_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_8_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_8_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_BASEADDR 0x50000000
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_HIGHADDR 0x50000FFF
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_9 */
#define XPAR_AXI_BRAM_CTRL_9_DEVICE_ID 49
#define XPAR_AXI_BRAM_CTRL_9_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_9_ECC 0
#define XPAR_AXI_BRAM_CTRL_9_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_9_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_9_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_9_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_9_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_9_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_9_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_9_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_BASEADDR 0x52000000
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_HIGHADDR 0x52000FFF
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral AXI_BRAM_CTRL_RESULTS */
#define XPAR_AXI_BRAM_CTRL_RESULTS_DEVICE_ID 50
#define XPAR_AXI_BRAM_CTRL_RESULTS_DATA_WIDTH 32
#define XPAR_AXI_BRAM_CTRL_RESULTS_ECC 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_FAULT_INJECT 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_CE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_UE_FAILING_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_ECC_STATUS_REGISTERS 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_CE_COUNTER_WIDTH 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_ECC_ONOFF_REGISTER 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_ECC_ONOFF_RESET_VALUE 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_WRITE_ACCESS 0
#define XPAR_AXI_BRAM_CTRL_RESULTS_S_AXI_BASEADDR 0x7E026000
#define XPAR_AXI_BRAM_CTRL_RESULTS_S_AXI_HIGHADDR 0x7E026FFF
#define XPAR_AXI_BRAM_CTRL_RESULTS_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_AXI_BRAM_CTRL_RESULTS_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_0_WRITE_ACCESS 0
#define XPAR_BRAM_0_BASEADDR 0x40000000
#define XPAR_BRAM_0_HIGHADDR 0x40000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_BRAM_1_DEVICE_ID XPAR_AXI_BRAM_CTRL_1_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32
#define XPAR_BRAM_1_ECC 0
#define XPAR_BRAM_1_FAULT_INJECT 0
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_1_WRITE_ACCESS 0
#define XPAR_BRAM_1_BASEADDR 0x42000000
#define XPAR_BRAM_1_HIGHADDR 0x42000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_10 */
#define XPAR_BRAM_2_DEVICE_ID XPAR_AXI_BRAM_CTRL_10_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32
#define XPAR_BRAM_2_ECC 0
#define XPAR_BRAM_2_FAULT_INJECT 0
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_2_WRITE_ACCESS 0
#define XPAR_BRAM_2_BASEADDR 0x54000000
#define XPAR_BRAM_2_HIGHADDR 0x54000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_11 */
#define XPAR_BRAM_3_DEVICE_ID XPAR_AXI_BRAM_CTRL_11_DEVICE_ID
#define XPAR_BRAM_3_DATA_WIDTH 32
#define XPAR_BRAM_3_ECC 0
#define XPAR_BRAM_3_FAULT_INJECT 0
#define XPAR_BRAM_3_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_3_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_3_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_3_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_3_WRITE_ACCESS 0
#define XPAR_BRAM_3_BASEADDR 0x56000000
#define XPAR_BRAM_3_HIGHADDR 0x56000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_12 */
#define XPAR_BRAM_4_DEVICE_ID XPAR_AXI_BRAM_CTRL_12_DEVICE_ID
#define XPAR_BRAM_4_DATA_WIDTH 32
#define XPAR_BRAM_4_ECC 0
#define XPAR_BRAM_4_FAULT_INJECT 0
#define XPAR_BRAM_4_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_4_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_4_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_4_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_4_WRITE_ACCESS 0
#define XPAR_BRAM_4_BASEADDR 0x58000000
#define XPAR_BRAM_4_HIGHADDR 0x58000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_13 */
#define XPAR_BRAM_5_DEVICE_ID XPAR_AXI_BRAM_CTRL_13_DEVICE_ID
#define XPAR_BRAM_5_DATA_WIDTH 32
#define XPAR_BRAM_5_ECC 0
#define XPAR_BRAM_5_FAULT_INJECT 0
#define XPAR_BRAM_5_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_5_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_5_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_5_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_5_WRITE_ACCESS 0
#define XPAR_BRAM_5_BASEADDR 0x5A000000
#define XPAR_BRAM_5_HIGHADDR 0x5A000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_14 */
#define XPAR_BRAM_6_DEVICE_ID XPAR_AXI_BRAM_CTRL_14_DEVICE_ID
#define XPAR_BRAM_6_DATA_WIDTH 32
#define XPAR_BRAM_6_ECC 0
#define XPAR_BRAM_6_FAULT_INJECT 0
#define XPAR_BRAM_6_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_6_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_6_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_6_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_6_WRITE_ACCESS 0
#define XPAR_BRAM_6_BASEADDR 0x5C000000
#define XPAR_BRAM_6_HIGHADDR 0x5C000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_15 */
#define XPAR_BRAM_7_DEVICE_ID XPAR_AXI_BRAM_CTRL_15_DEVICE_ID
#define XPAR_BRAM_7_DATA_WIDTH 32
#define XPAR_BRAM_7_ECC 0
#define XPAR_BRAM_7_FAULT_INJECT 0
#define XPAR_BRAM_7_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_7_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_7_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_7_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_7_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_7_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_7_WRITE_ACCESS 0
#define XPAR_BRAM_7_BASEADDR 0x5E000000
#define XPAR_BRAM_7_HIGHADDR 0x5E000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_16 */
#define XPAR_BRAM_8_DEVICE_ID XPAR_AXI_BRAM_CTRL_16_DEVICE_ID
#define XPAR_BRAM_8_DATA_WIDTH 32
#define XPAR_BRAM_8_ECC 0
#define XPAR_BRAM_8_FAULT_INJECT 0
#define XPAR_BRAM_8_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_8_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_8_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_8_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_8_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_8_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_8_WRITE_ACCESS 0
#define XPAR_BRAM_8_BASEADDR 0x60000000
#define XPAR_BRAM_8_HIGHADDR 0x60000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_17 */
#define XPAR_BRAM_9_DEVICE_ID XPAR_AXI_BRAM_CTRL_17_DEVICE_ID
#define XPAR_BRAM_9_DATA_WIDTH 32
#define XPAR_BRAM_9_ECC 0
#define XPAR_BRAM_9_FAULT_INJECT 0
#define XPAR_BRAM_9_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_9_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_9_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_9_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_9_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_9_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_9_WRITE_ACCESS 0
#define XPAR_BRAM_9_BASEADDR 0x62000000
#define XPAR_BRAM_9_HIGHADDR 0x62000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_18 */
#define XPAR_BRAM_10_DEVICE_ID XPAR_AXI_BRAM_CTRL_18_DEVICE_ID
#define XPAR_BRAM_10_DATA_WIDTH 32
#define XPAR_BRAM_10_ECC 0
#define XPAR_BRAM_10_FAULT_INJECT 0
#define XPAR_BRAM_10_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_10_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_10_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_10_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_10_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_10_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_10_WRITE_ACCESS 0
#define XPAR_BRAM_10_BASEADDR 0x64000000
#define XPAR_BRAM_10_HIGHADDR 0x64000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_19 */
#define XPAR_BRAM_11_DEVICE_ID XPAR_AXI_BRAM_CTRL_19_DEVICE_ID
#define XPAR_BRAM_11_DATA_WIDTH 32
#define XPAR_BRAM_11_ECC 0
#define XPAR_BRAM_11_FAULT_INJECT 0
#define XPAR_BRAM_11_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_11_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_11_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_11_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_11_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_11_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_11_WRITE_ACCESS 0
#define XPAR_BRAM_11_BASEADDR 0x66000000
#define XPAR_BRAM_11_HIGHADDR 0x66000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_BRAM_12_DEVICE_ID XPAR_AXI_BRAM_CTRL_2_DEVICE_ID
#define XPAR_BRAM_12_DATA_WIDTH 32
#define XPAR_BRAM_12_ECC 0
#define XPAR_BRAM_12_FAULT_INJECT 0
#define XPAR_BRAM_12_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_12_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_12_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_12_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_12_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_12_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_12_WRITE_ACCESS 0
#define XPAR_BRAM_12_BASEADDR 0x44000000
#define XPAR_BRAM_12_HIGHADDR 0x44000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_20 */
#define XPAR_BRAM_13_DEVICE_ID XPAR_AXI_BRAM_CTRL_20_DEVICE_ID
#define XPAR_BRAM_13_DATA_WIDTH 32
#define XPAR_BRAM_13_ECC 0
#define XPAR_BRAM_13_FAULT_INJECT 0
#define XPAR_BRAM_13_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_13_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_13_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_13_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_13_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_13_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_13_WRITE_ACCESS 0
#define XPAR_BRAM_13_BASEADDR 0x68000000
#define XPAR_BRAM_13_HIGHADDR 0x68000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_21 */
#define XPAR_BRAM_14_DEVICE_ID XPAR_AXI_BRAM_CTRL_21_DEVICE_ID
#define XPAR_BRAM_14_DATA_WIDTH 32
#define XPAR_BRAM_14_ECC 0
#define XPAR_BRAM_14_FAULT_INJECT 0
#define XPAR_BRAM_14_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_14_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_14_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_14_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_14_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_14_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_14_WRITE_ACCESS 0
#define XPAR_BRAM_14_BASEADDR 0x6A000000
#define XPAR_BRAM_14_HIGHADDR 0x6A000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_22 */
#define XPAR_BRAM_15_DEVICE_ID XPAR_AXI_BRAM_CTRL_22_DEVICE_ID
#define XPAR_BRAM_15_DATA_WIDTH 32
#define XPAR_BRAM_15_ECC 0
#define XPAR_BRAM_15_FAULT_INJECT 0
#define XPAR_BRAM_15_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_15_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_15_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_15_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_15_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_15_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_15_WRITE_ACCESS 0
#define XPAR_BRAM_15_BASEADDR 0x6C000000
#define XPAR_BRAM_15_HIGHADDR 0x6C000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_23 */
#define XPAR_BRAM_16_DEVICE_ID XPAR_AXI_BRAM_CTRL_23_DEVICE_ID
#define XPAR_BRAM_16_DATA_WIDTH 32
#define XPAR_BRAM_16_ECC 0
#define XPAR_BRAM_16_FAULT_INJECT 0
#define XPAR_BRAM_16_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_16_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_16_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_16_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_16_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_16_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_16_WRITE_ACCESS 0
#define XPAR_BRAM_16_BASEADDR 0x6E000000
#define XPAR_BRAM_16_HIGHADDR 0x6E000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_24 */
#define XPAR_BRAM_17_DEVICE_ID XPAR_AXI_BRAM_CTRL_24_DEVICE_ID
#define XPAR_BRAM_17_DATA_WIDTH 32
#define XPAR_BRAM_17_ECC 0
#define XPAR_BRAM_17_FAULT_INJECT 0
#define XPAR_BRAM_17_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_17_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_17_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_17_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_17_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_17_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_17_WRITE_ACCESS 0
#define XPAR_BRAM_17_BASEADDR 0x70000000
#define XPAR_BRAM_17_HIGHADDR 0x70000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_25 */
#define XPAR_BRAM_18_DEVICE_ID XPAR_AXI_BRAM_CTRL_25_DEVICE_ID
#define XPAR_BRAM_18_DATA_WIDTH 32
#define XPAR_BRAM_18_ECC 0
#define XPAR_BRAM_18_FAULT_INJECT 0
#define XPAR_BRAM_18_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_18_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_18_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_18_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_18_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_18_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_18_WRITE_ACCESS 0
#define XPAR_BRAM_18_BASEADDR 0x72000000
#define XPAR_BRAM_18_HIGHADDR 0x72000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_26 */
#define XPAR_BRAM_19_DEVICE_ID XPAR_AXI_BRAM_CTRL_26_DEVICE_ID
#define XPAR_BRAM_19_DATA_WIDTH 32
#define XPAR_BRAM_19_ECC 0
#define XPAR_BRAM_19_FAULT_INJECT 0
#define XPAR_BRAM_19_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_19_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_19_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_19_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_19_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_19_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_19_WRITE_ACCESS 0
#define XPAR_BRAM_19_BASEADDR 0x74000000
#define XPAR_BRAM_19_HIGHADDR 0x74000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_27 */
#define XPAR_BRAM_20_DEVICE_ID XPAR_AXI_BRAM_CTRL_27_DEVICE_ID
#define XPAR_BRAM_20_DATA_WIDTH 32
#define XPAR_BRAM_20_ECC 0
#define XPAR_BRAM_20_FAULT_INJECT 0
#define XPAR_BRAM_20_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_20_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_20_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_20_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_20_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_20_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_20_WRITE_ACCESS 0
#define XPAR_BRAM_20_BASEADDR 0x76000000
#define XPAR_BRAM_20_HIGHADDR 0x76000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_28 */
#define XPAR_BRAM_21_DEVICE_ID XPAR_AXI_BRAM_CTRL_28_DEVICE_ID
#define XPAR_BRAM_21_DATA_WIDTH 32
#define XPAR_BRAM_21_ECC 0
#define XPAR_BRAM_21_FAULT_INJECT 0
#define XPAR_BRAM_21_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_21_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_21_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_21_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_21_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_21_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_21_WRITE_ACCESS 0
#define XPAR_BRAM_21_BASEADDR 0x78000000
#define XPAR_BRAM_21_HIGHADDR 0x78000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_29 */
#define XPAR_BRAM_22_DEVICE_ID XPAR_AXI_BRAM_CTRL_29_DEVICE_ID
#define XPAR_BRAM_22_DATA_WIDTH 32
#define XPAR_BRAM_22_ECC 0
#define XPAR_BRAM_22_FAULT_INJECT 0
#define XPAR_BRAM_22_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_22_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_22_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_22_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_22_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_22_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_22_WRITE_ACCESS 0
#define XPAR_BRAM_22_BASEADDR 0x7A000000
#define XPAR_BRAM_22_HIGHADDR 0x7A000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_BRAM_23_DEVICE_ID XPAR_AXI_BRAM_CTRL_3_DEVICE_ID
#define XPAR_BRAM_23_DATA_WIDTH 32
#define XPAR_BRAM_23_ECC 0
#define XPAR_BRAM_23_FAULT_INJECT 0
#define XPAR_BRAM_23_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_23_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_23_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_23_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_23_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_23_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_23_WRITE_ACCESS 0
#define XPAR_BRAM_23_BASEADDR 0x46000000
#define XPAR_BRAM_23_HIGHADDR 0x46000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_30 */
#define XPAR_BRAM_24_DEVICE_ID XPAR_AXI_BRAM_CTRL_30_DEVICE_ID
#define XPAR_BRAM_24_DATA_WIDTH 32
#define XPAR_BRAM_24_ECC 0
#define XPAR_BRAM_24_FAULT_INJECT 0
#define XPAR_BRAM_24_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_24_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_24_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_24_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_24_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_24_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_24_WRITE_ACCESS 0
#define XPAR_BRAM_24_BASEADDR 0x7C000000
#define XPAR_BRAM_24_HIGHADDR 0x7C000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_31 */
#define XPAR_BRAM_25_DEVICE_ID XPAR_AXI_BRAM_CTRL_31_DEVICE_ID
#define XPAR_BRAM_25_DATA_WIDTH 32
#define XPAR_BRAM_25_ECC 0
#define XPAR_BRAM_25_FAULT_INJECT 0
#define XPAR_BRAM_25_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_25_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_25_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_25_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_25_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_25_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_25_WRITE_ACCESS 0
#define XPAR_BRAM_25_BASEADDR 0x7E000000
#define XPAR_BRAM_25_HIGHADDR 0x7E000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_32 */
#define XPAR_BRAM_26_DEVICE_ID XPAR_AXI_BRAM_CTRL_32_DEVICE_ID
#define XPAR_BRAM_26_DATA_WIDTH 32
#define XPAR_BRAM_26_ECC 0
#define XPAR_BRAM_26_FAULT_INJECT 0
#define XPAR_BRAM_26_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_26_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_26_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_26_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_26_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_26_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_26_WRITE_ACCESS 0
#define XPAR_BRAM_26_BASEADDR 0x7E002000
#define XPAR_BRAM_26_HIGHADDR 0x7E002FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_33 */
#define XPAR_BRAM_27_DEVICE_ID XPAR_AXI_BRAM_CTRL_33_DEVICE_ID
#define XPAR_BRAM_27_DATA_WIDTH 32
#define XPAR_BRAM_27_ECC 0
#define XPAR_BRAM_27_FAULT_INJECT 0
#define XPAR_BRAM_27_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_27_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_27_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_27_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_27_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_27_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_27_WRITE_ACCESS 0
#define XPAR_BRAM_27_BASEADDR 0x7E004000
#define XPAR_BRAM_27_HIGHADDR 0x7E004FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_34 */
#define XPAR_BRAM_28_DEVICE_ID XPAR_AXI_BRAM_CTRL_34_DEVICE_ID
#define XPAR_BRAM_28_DATA_WIDTH 32
#define XPAR_BRAM_28_ECC 0
#define XPAR_BRAM_28_FAULT_INJECT 0
#define XPAR_BRAM_28_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_28_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_28_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_28_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_28_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_28_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_28_WRITE_ACCESS 0
#define XPAR_BRAM_28_BASEADDR 0x7E006000
#define XPAR_BRAM_28_HIGHADDR 0x7E006FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_35 */
#define XPAR_BRAM_29_DEVICE_ID XPAR_AXI_BRAM_CTRL_35_DEVICE_ID
#define XPAR_BRAM_29_DATA_WIDTH 32
#define XPAR_BRAM_29_ECC 0
#define XPAR_BRAM_29_FAULT_INJECT 0
#define XPAR_BRAM_29_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_29_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_29_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_29_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_29_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_29_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_29_WRITE_ACCESS 0
#define XPAR_BRAM_29_BASEADDR 0x7E008000
#define XPAR_BRAM_29_HIGHADDR 0x7E008FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_36 */
#define XPAR_BRAM_30_DEVICE_ID XPAR_AXI_BRAM_CTRL_36_DEVICE_ID
#define XPAR_BRAM_30_DATA_WIDTH 32
#define XPAR_BRAM_30_ECC 0
#define XPAR_BRAM_30_FAULT_INJECT 0
#define XPAR_BRAM_30_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_30_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_30_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_30_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_30_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_30_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_30_WRITE_ACCESS 0
#define XPAR_BRAM_30_BASEADDR 0x7E00A000
#define XPAR_BRAM_30_HIGHADDR 0x7E00AFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_37 */
#define XPAR_BRAM_31_DEVICE_ID XPAR_AXI_BRAM_CTRL_37_DEVICE_ID
#define XPAR_BRAM_31_DATA_WIDTH 32
#define XPAR_BRAM_31_ECC 0
#define XPAR_BRAM_31_FAULT_INJECT 0
#define XPAR_BRAM_31_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_31_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_31_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_31_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_31_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_31_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_31_WRITE_ACCESS 0
#define XPAR_BRAM_31_BASEADDR 0x7E00C000
#define XPAR_BRAM_31_HIGHADDR 0x7E00CFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_38 */
#define XPAR_BRAM_32_DEVICE_ID XPAR_AXI_BRAM_CTRL_38_DEVICE_ID
#define XPAR_BRAM_32_DATA_WIDTH 32
#define XPAR_BRAM_32_ECC 0
#define XPAR_BRAM_32_FAULT_INJECT 0
#define XPAR_BRAM_32_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_32_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_32_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_32_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_32_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_32_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_32_WRITE_ACCESS 0
#define XPAR_BRAM_32_BASEADDR 0x7E00E000
#define XPAR_BRAM_32_HIGHADDR 0x7E00EFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_39 */
#define XPAR_BRAM_33_DEVICE_ID XPAR_AXI_BRAM_CTRL_39_DEVICE_ID
#define XPAR_BRAM_33_DATA_WIDTH 32
#define XPAR_BRAM_33_ECC 0
#define XPAR_BRAM_33_FAULT_INJECT 0
#define XPAR_BRAM_33_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_33_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_33_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_33_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_33_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_33_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_33_WRITE_ACCESS 0
#define XPAR_BRAM_33_BASEADDR 0x7E010000
#define XPAR_BRAM_33_HIGHADDR 0x7E010FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_BRAM_34_DEVICE_ID XPAR_AXI_BRAM_CTRL_4_DEVICE_ID
#define XPAR_BRAM_34_DATA_WIDTH 32
#define XPAR_BRAM_34_ECC 0
#define XPAR_BRAM_34_FAULT_INJECT 0
#define XPAR_BRAM_34_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_34_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_34_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_34_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_34_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_34_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_34_WRITE_ACCESS 0
#define XPAR_BRAM_34_BASEADDR 0x48000000
#define XPAR_BRAM_34_HIGHADDR 0x48000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_40 */
#define XPAR_BRAM_35_DEVICE_ID XPAR_AXI_BRAM_CTRL_40_DEVICE_ID
#define XPAR_BRAM_35_DATA_WIDTH 32
#define XPAR_BRAM_35_ECC 0
#define XPAR_BRAM_35_FAULT_INJECT 0
#define XPAR_BRAM_35_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_35_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_35_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_35_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_35_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_35_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_35_WRITE_ACCESS 0
#define XPAR_BRAM_35_BASEADDR 0x7E012000
#define XPAR_BRAM_35_HIGHADDR 0x7E012FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_41 */
#define XPAR_BRAM_36_DEVICE_ID XPAR_AXI_BRAM_CTRL_41_DEVICE_ID
#define XPAR_BRAM_36_DATA_WIDTH 32
#define XPAR_BRAM_36_ECC 0
#define XPAR_BRAM_36_FAULT_INJECT 0
#define XPAR_BRAM_36_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_36_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_36_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_36_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_36_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_36_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_36_WRITE_ACCESS 0
#define XPAR_BRAM_36_BASEADDR 0x7E014000
#define XPAR_BRAM_36_HIGHADDR 0x7E014FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_42 */
#define XPAR_BRAM_37_DEVICE_ID XPAR_AXI_BRAM_CTRL_42_DEVICE_ID
#define XPAR_BRAM_37_DATA_WIDTH 32
#define XPAR_BRAM_37_ECC 0
#define XPAR_BRAM_37_FAULT_INJECT 0
#define XPAR_BRAM_37_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_37_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_37_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_37_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_37_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_37_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_37_WRITE_ACCESS 0
#define XPAR_BRAM_37_BASEADDR 0x7E016000
#define XPAR_BRAM_37_HIGHADDR 0x7E016FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_43 */
#define XPAR_BRAM_38_DEVICE_ID XPAR_AXI_BRAM_CTRL_43_DEVICE_ID
#define XPAR_BRAM_38_DATA_WIDTH 32
#define XPAR_BRAM_38_ECC 0
#define XPAR_BRAM_38_FAULT_INJECT 0
#define XPAR_BRAM_38_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_38_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_38_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_38_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_38_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_38_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_38_WRITE_ACCESS 0
#define XPAR_BRAM_38_BASEADDR 0x7E018000
#define XPAR_BRAM_38_HIGHADDR 0x7E018FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_44 */
#define XPAR_BRAM_39_DEVICE_ID XPAR_AXI_BRAM_CTRL_44_DEVICE_ID
#define XPAR_BRAM_39_DATA_WIDTH 32
#define XPAR_BRAM_39_ECC 0
#define XPAR_BRAM_39_FAULT_INJECT 0
#define XPAR_BRAM_39_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_39_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_39_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_39_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_39_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_39_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_39_WRITE_ACCESS 0
#define XPAR_BRAM_39_BASEADDR 0x7E01A000
#define XPAR_BRAM_39_HIGHADDR 0x7E01AFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_45 */
#define XPAR_BRAM_40_DEVICE_ID XPAR_AXI_BRAM_CTRL_45_DEVICE_ID
#define XPAR_BRAM_40_DATA_WIDTH 32
#define XPAR_BRAM_40_ECC 0
#define XPAR_BRAM_40_FAULT_INJECT 0
#define XPAR_BRAM_40_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_40_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_40_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_40_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_40_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_40_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_40_WRITE_ACCESS 0
#define XPAR_BRAM_40_BASEADDR 0x7E01C000
#define XPAR_BRAM_40_HIGHADDR 0x7E01CFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_46 */
#define XPAR_BRAM_41_DEVICE_ID XPAR_AXI_BRAM_CTRL_46_DEVICE_ID
#define XPAR_BRAM_41_DATA_WIDTH 32
#define XPAR_BRAM_41_ECC 0
#define XPAR_BRAM_41_FAULT_INJECT 0
#define XPAR_BRAM_41_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_41_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_41_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_41_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_41_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_41_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_41_WRITE_ACCESS 0
#define XPAR_BRAM_41_BASEADDR 0x7E01E000
#define XPAR_BRAM_41_HIGHADDR 0x7E01EFFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_47 */
#define XPAR_BRAM_42_DEVICE_ID XPAR_AXI_BRAM_CTRL_47_DEVICE_ID
#define XPAR_BRAM_42_DATA_WIDTH 32
#define XPAR_BRAM_42_ECC 0
#define XPAR_BRAM_42_FAULT_INJECT 0
#define XPAR_BRAM_42_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_42_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_42_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_42_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_42_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_42_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_42_WRITE_ACCESS 0
#define XPAR_BRAM_42_BASEADDR 0x7E020000
#define XPAR_BRAM_42_HIGHADDR 0x7E020FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_48 */
#define XPAR_BRAM_43_DEVICE_ID XPAR_AXI_BRAM_CTRL_48_DEVICE_ID
#define XPAR_BRAM_43_DATA_WIDTH 32
#define XPAR_BRAM_43_ECC 0
#define XPAR_BRAM_43_FAULT_INJECT 0
#define XPAR_BRAM_43_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_43_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_43_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_43_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_43_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_43_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_43_WRITE_ACCESS 0
#define XPAR_BRAM_43_BASEADDR 0x7E022000
#define XPAR_BRAM_43_HIGHADDR 0x7E022FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_49 */
#define XPAR_BRAM_44_DEVICE_ID XPAR_AXI_BRAM_CTRL_49_DEVICE_ID
#define XPAR_BRAM_44_DATA_WIDTH 32
#define XPAR_BRAM_44_ECC 0
#define XPAR_BRAM_44_FAULT_INJECT 0
#define XPAR_BRAM_44_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_44_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_44_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_44_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_44_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_44_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_44_WRITE_ACCESS 0
#define XPAR_BRAM_44_BASEADDR 0x7E024000
#define XPAR_BRAM_44_HIGHADDR 0x7E024FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_BRAM_45_DEVICE_ID XPAR_AXI_BRAM_CTRL_5_DEVICE_ID
#define XPAR_BRAM_45_DATA_WIDTH 32
#define XPAR_BRAM_45_ECC 0
#define XPAR_BRAM_45_FAULT_INJECT 0
#define XPAR_BRAM_45_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_45_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_45_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_45_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_45_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_45_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_45_WRITE_ACCESS 0
#define XPAR_BRAM_45_BASEADDR 0x4A000000
#define XPAR_BRAM_45_HIGHADDR 0x4A000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_BRAM_46_DEVICE_ID XPAR_AXI_BRAM_CTRL_6_DEVICE_ID
#define XPAR_BRAM_46_DATA_WIDTH 32
#define XPAR_BRAM_46_ECC 0
#define XPAR_BRAM_46_FAULT_INJECT 0
#define XPAR_BRAM_46_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_46_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_46_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_46_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_46_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_46_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_46_WRITE_ACCESS 0
#define XPAR_BRAM_46_BASEADDR 0x4C000000
#define XPAR_BRAM_46_HIGHADDR 0x4C000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_BRAM_47_DEVICE_ID XPAR_AXI_BRAM_CTRL_7_DEVICE_ID
#define XPAR_BRAM_47_DATA_WIDTH 32
#define XPAR_BRAM_47_ECC 0
#define XPAR_BRAM_47_FAULT_INJECT 0
#define XPAR_BRAM_47_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_47_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_47_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_47_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_47_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_47_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_47_WRITE_ACCESS 0
#define XPAR_BRAM_47_BASEADDR 0x4E000000
#define XPAR_BRAM_47_HIGHADDR 0x4E000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_8 */
#define XPAR_BRAM_48_DEVICE_ID XPAR_AXI_BRAM_CTRL_8_DEVICE_ID
#define XPAR_BRAM_48_DATA_WIDTH 32
#define XPAR_BRAM_48_ECC 0
#define XPAR_BRAM_48_FAULT_INJECT 0
#define XPAR_BRAM_48_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_48_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_48_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_48_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_48_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_48_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_48_WRITE_ACCESS 0
#define XPAR_BRAM_48_BASEADDR 0x50000000
#define XPAR_BRAM_48_HIGHADDR 0x50000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_9 */
#define XPAR_BRAM_49_DEVICE_ID XPAR_AXI_BRAM_CTRL_9_DEVICE_ID
#define XPAR_BRAM_49_DATA_WIDTH 32
#define XPAR_BRAM_49_ECC 0
#define XPAR_BRAM_49_FAULT_INJECT 0
#define XPAR_BRAM_49_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_49_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_49_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_49_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_49_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_49_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_49_WRITE_ACCESS 0
#define XPAR_BRAM_49_BASEADDR 0x52000000
#define XPAR_BRAM_49_HIGHADDR 0x52000FFF

/* Canonical definitions for peripheral AXI_BRAM_CTRL_RESULTS */
#define XPAR_BRAM_50_DEVICE_ID XPAR_AXI_BRAM_CTRL_RESULTS_DEVICE_ID
#define XPAR_BRAM_50_DATA_WIDTH 32
#define XPAR_BRAM_50_ECC 0
#define XPAR_BRAM_50_FAULT_INJECT 0
#define XPAR_BRAM_50_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_50_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_50_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_50_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_50_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_50_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_50_WRITE_ACCESS 0
#define XPAR_BRAM_50_BASEADDR 0x7E026000
#define XPAR_BRAM_50_HIGHADDR 0x7E026FFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50


/******************************************************************/

/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50


/******************************************************************/


/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x1FFFFFFF


/* Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver NEEDLEMANWUNSCH */
#define XPAR_XNEEDLEMANWUNSCH_NUM_INSTANCES 1

/* Definitions for peripheral NEEDLEMANWUNSCH_0 */
#define XPAR_NEEDLEMANWUNSCH_0_DEVICE_ID 0
#define XPAR_NEEDLEMANWUNSCH_0_S_AXI_AXILITES_BASEADDR 0x43C00000
#define XPAR_NEEDLEMANWUNSCH_0_S_AXI_AXILITES_HIGHADDR 0x43C0FFFF


/******************************************************************/

/* Canonical definitions for peripheral NEEDLEMANWUNSCH_0 */
#define XPAR_XNEEDLEMANWUNSCH_0_DEVICE_ID XPAR_NEEDLEMANWUNSCH_0_DEVICE_ID
#define XPAR_XNEEDLEMANWUNSCH_0_S_AXI_AXILITES_BASEADDR 0x43C00000
#define XPAR_XNEEDLEMANWUNSCH_0_S_AXI_AXILITES_HIGHADDR 0x43C0FFFF


/******************************************************************/

/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 0


/******************************************************************/


/***Definitions for Core_nIRQ/nFIQ interrupts ****/
/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FF
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FF
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_PS7_SD_0_HAS_CD 1
#define XPAR_PS7_SD_0_HAS_WP 1


/******************************************************************/

/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 1


/******************************************************************/

/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 3

/* Definitions for peripheral PS7_TTC_0 */
#define XPAR_PS7_TTC_0_DEVICE_ID 0
#define XPAR_PS7_TTC_0_BASEADDR 0XF8001000
#define XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ 111111115
#define XPAR_PS7_TTC_0_TTC_CLK_CLKSRC 0
#define XPAR_PS7_TTC_1_DEVICE_ID 1
#define XPAR_PS7_TTC_1_BASEADDR 0XF8001004
#define XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ 111111115
#define XPAR_PS7_TTC_1_TTC_CLK_CLKSRC 0
#define XPAR_PS7_TTC_2_DEVICE_ID 2
#define XPAR_PS7_TTC_2_BASEADDR 0XF8001008
#define XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ 111111115
#define XPAR_PS7_TTC_2_TTC_CLK_CLKSRC 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PS7_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xF8001000
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 111111115
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PS7_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xF8001004
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 111111115
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PS7_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xF8001008
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 111111115
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 50000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

